### PR TITLE
usc-036.id430c44da-f59a-11ee-8591-ff101ca1cce5.cgel

### PR DESCRIPTION
**Pull request by nschneid**
"The Secretary may pay an allowance under this section for the purchase of uniforms to any Department police officer who is required to wear a prescribed uniform in the performance of official duties."

Not sure about "allowance...**for the purchase of uniforms**" but it feels complementy?

### CODE REVIEW

**Comment by nschneid** [comment]
The validator complains about the gap in the Nom though.

Another option is to have no gap and simply say there is a Mod before a Comp (as this is not a VP). Head:[allowance Mod:[under this section]] Comp:[for the purchase of uniforms]. The validator doesn't complain about that.

**Comment by bwaldon** [comment]
> Another option is to have no gap and simply say there is a Mod before a Comp (as this is not a VP where we are strict about the placement of comps next to the verb). 

Taking a look through the CGELBank data, it seems like the `:Postnucleus` function label almost always appears on constituents that are displaced due to an intervening constituent functioning as an argument. That gives me a bit more confidence in this option.

**Comment by nschneid** [comment]
In which option? (Are there analogous examples of Postnucleus within a Nom?)

**Comment by bwaldon** [comment]
What I mean is:

Let's go with this structure: `Head:[allowance Mod:[under this section]] Comp:[for the purchase of uniforms]` 

There are -- as far as I can see -- no examples of `:Postnucleus` within a `Nom` whereby the displaced constituent (the one receiving the `:Postnucleus` label) is separated from its canonical argument position by an intervening adjunct. The intervening constituent seems to always be an argument. (E.g.: https://github.com/nert-nlp/cgel/blob/004d8abb92d1e5364b8fa9b2a80f6f98e1aeff75/datasets/oneoff/pdf/kamala.pdf).

**Pull request merged**
