### PR TITLE
Cache CGEL and texlive-latex-extra dependencies

### PR DESCRIPTION
**Pull request by m3ru**
This will have to be changed so that it does not ignore main (dependencies get cached on main) and then changed back so that only new branches run the action. The cached dependencies will work on any upstream branch.

### CODE REVIEW

**Comment by bwaldon** [comment]
What if we ran a separate, one-time action on `main`, just to create the cache?

**Comment by m3ru** [comment]
I may be wrong but making a one time action and editing this so it creates the cache then changing it back seem equivalent. I can do either.

**Comment by bwaldon** [comment]
Oh got it. I'd prefer making the one time action and calling it something like `create_texlive_cache.yml`, only because I think it will be slightly easier for us (and others) to retrace our steps for setting this up. You might be able to set the trigger by restricting the `paths` argument to the action file itself (i.e., action runs when `create_texlive_cache.yml` is pushed to the branch). But that might not work, in which case I think the trigger could be something like:

```
on:
  push:
    paths:
      - .github/workflows/TEXLIVE_CACHE_INIT
    branches:
      - main  
```

... where `TEXLIVE_CACHE_INIT` is a vacuous file pushed to `main` once.

**Comment by m3ru** [comment]
closed for new updates

**Pull request closed without merging**
